### PR TITLE
runFinal improvements

### PR DESCRIPTION
**Pull request by jalimena**
This PR adds a few options when running `fccanalysis final analysis_final.py`, namely:

1. The option to scale the number of events printed after each selection by the target integrated luminosity and the cross section (by introducing new variables called `intLumi` and `doScale`)
2. The option to save the number of events (scaled or not) and their uncertainties in a latex table (with the variable `saveTabular`)
3. The option to rename the selections in an easier-to-read way for that table (with the variable `cutLabels`)

An example of how to use these new variables is provided in `examples/FCCee/bsm/LLPs/DisplacedHNL/analysis_final.py`

### CODE REVIEW

**Comment by jalimena** [comment]
tagging @vvolkl  and @clementhelsens thanks!

**Review by vvolkl — APPROVED** [review]
Looks good to me, thanks a lot! Waiting for Clement to take a look as well.

**Review by clementhelsens — APPROVED** [review]
thanks @jalimena , looks good. sorry for late actions, we are in the middle of the hands on tuto

**Comment by jalimena** [comment]
thanks! yeah no worries, hope the tutorial is going well!

**Pull request merged**
