### PR TITLE
FCCAnalyses::MCParticle::get_indices, for exclusive and inclusive decays

### PR DESCRIPTION
**Pull request by jalimena**
This PR replaces MCParticle::get_indices_ExclusiveDecay with MCParticle::get_indices. The new function has the ability to look at exclusive decays (it requires that it finds the exact list of daughter pdgids) or inclusive decays (it looks at the MCParticles for the provided set of daughter pdgids, regardless if those are all of the decay products or not). I also added a boolean for this new function such that you can also look for the charge conjugates of the daughter particles. I've tested that this function behaves as I expect in two different decay chains.

This PR should take the place of #114 , which I messed up :/

When we last left #114, @vvolkl asked me to add a template parameter and explicitly instantiate both explicit and implicit, in order to not break the analyses that use get_indices_ExclusiveDecay. He started to show me how to do this, but I didn't fully understand how to incorporate the chargeConjugateDaughters parameter, see https://github.com/HEP-FCC/FCCAnalyses/pull/114#issuecomment-1014617219. I hope @vvolkl  can finish showing me what to do, and then I can update this PR.

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi @jalimena,
sorry for the delayed reply. After some discussions, I think it's not so important to keep the exact signature, this repo isn't completely stable yet anyway. Can you still check that the old signature `get_indices_ExclusiveDecay_MotherByIndex` is replaced everywhere in this repo and in FCCeePhysicsPerformance?

**Review by vvolkl — APPROVED** [review]
Looks good to me, thanks!

**Comment by vvolkl** [comment]
In FCCeePhysicsPerformance, there are still three occurences of the old signature: https://github.com/HEP-FCC/FCCeePhysicsPerformance/search?q=get_indices_ExclusiveDecay_MotherByIndex

**Comment by EmanuelPerez** [comment]
Thanks Juliette ! As the functionality is preserved, I suggest to keep the old method but make it "empty", with just a printout as I wrote above, and maybe a reference to this PR. This will make the transition smooth and easy for anyone who may be using the old method.

**Comment by vvolkl** [comment]
Hi @EmanuelPerez,

thanks for confirming that it is better to keep compatibility. I just didn't want to hold up this PR any longer, but that is good motivation to put in the effort. I haven't tested it exhaustively yet, but with the slight overhead of copying the arguments it is easy to keep the old signatures: https://github.com/HEP-FCC/FCCAnalyses/pull/162

(And a lot of copying can still be avoided by instantiating this struct only once in the beginning instead of at each event)

With "instability" I was referring mostly to the recent changes in #142 which already require a lot of changes in user code, but it seems that this can be avoided too (#164)
Let me know if the proposed solution for the exclusiveDecays signature seems ok.

**Comment by jalimena** [comment]
ok great, with these other PRs, I think we are set. i think we should merge #162

**Comment by EmanuelPerez** [comment]
Dear Valentin, many thanks for your efforts ! Yes, PR162 looks perfect, I agree that we should merge it. Thanks !!

**Pull request merged**
