### PR TITLE
add url instead of afs

### PR DESCRIPTION
**Pull request by clementhelsens**

### CODE REVIEW

**Comment by clementhelsens** [comment]
@vvolkl , @gganis , I replaced the afs by url, please let me know what you think

**Review by gganis — COMMENTED** [review]
Looks good, though it overwrites the setting of  FCCDICTSDIR ... cannot we couple the two?
I mean we can have as default FCCDICTSDIR = https://fcc-physics-events.web.cern.ch/fcc-physics-events/sharedFiles/
and the rest follows ... 
It would help to have the same  file structure under /afs/cern.ch/work/h/helsens/public/FCCDicts/ and  https://fcc-physics-events.web.cern.ch/fcc-physics-events/sharedFiles/ ...

**Comment by clementhelsens** [comment]
@gganis , I agree with you but I have limited time to implement this properly. could we patch like this and clean up later?

**Comment by gganis** [comment]
Fine with me, if it works in all cases.

**Comment by clementhelsens** [comment]
I have not tried on OSG though, on lxplus everything worked fine.

**Pull request merged**
