### PR TITLE
Adding exception printout in config file

### PR DESCRIPTION
**Pull request by atishelmanch**
Hello - I would propose adding a single printout statement in the configuration setup, as I found that without it, one may have trouble debugging issues. 

For example - when running with a particular configuration where I was accidentally including the same variable twice in the output tree, I was running the command:

```
fccanalysis run ZccH_stage1.py --output wzp6_ee_ccH_Hcc_ecm240.root --files-list /eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA/wzp6_ee_ccH_Hcc_ecm240/events_056080797.root --ncpus 64 --nev 100
```

and receiving the output:

```
----> Load cxx analyzers from libFCCAnalyses... 
--------------loading analysis file   /afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/ZccH_stage1.py
batch: 0
EOSoutput: 0
name: ZccH_4jetsRequired
njets: 4
run
The variable <outputDirEos> is optional in your analysis.py file, return default empty string
----> Running with user defined list of files (either locally or from batch)
----> Create dataframe object from files: 
    /eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA/wzp6_ee_ccH_Hcc_ecm240/events_056080797.root
----> nevents original=0  local=100
The variable <geometryFile> is optional in your analysis.py file, return default value empty string
The variable <readoutName> is optional in your analysis.py file, return default value empty string
----> Init done, about to run 100 events on 1 CPUs
============running the old way
Traceback (most recent call last):
  File "/afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/FCCAnalyses/bin/fccanalysis", line 37, in <module>
    run(parser)
  File "/afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/FCCAnalyses/config/FCCAnalysisRun.py", line 1102, in run
    if args.final:
AttributeError: 'Namespace' object has no attribute 'final'
```

Where it's not obvious what the error is - it just appears that I'm running with the "old" method.

When adding the exception printout, the error became obvious:

```
----> Load cxx analyzers from libFCCAnalyses... 
--------------loading analysis file   /afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/ZccH_stage1.py
batch: 0
EOSoutput: 0
name: ZccH_4jetsRequired
njets: 4
run
The variable <outputDirEos> is optional in your analysis.py file, return default empty string
----> Running with user defined list of files (either locally or from batch)
----> Create dataframe object from files: 
    /eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA/wzp6_ee_ccH_Hcc_ecm240/events_056080797.root
----> nevents original=0  local=100
The variable <geometryFile> is optional in your analysis.py file, return default value empty string
The variable <readoutName> is optional in your analysis.py file, return default value empty string
----> Init done, about to run 100 events on 1 CPUs
Exception: Template method resolution failed:
  none of the 3 overloaded methods succeeded. Full details:
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, initializer_list<string> columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    TypeError: could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    logic_error: Error: column "jet_nmu" was passed to Snapshot twice. This is not supported: only one of the columns would be readable with RDataFrame.
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, basic_string_view<char,char_traits<char> > columnNameRegexp = "", const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    TypeError: could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    logic_error: Error: column "jet_nmu" was passed to Snapshot twice. This is not supported: only one of the columns would be readable with RDataFrame.
  Failed to instantiate "Snapshot(std::string,std::string,std::vector<string>*)"
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    logic_error: Error: column "jet_nmu" was passed to Snapshot twice. This is not supported: only one of the columns would be readable with RDataFrame.
============running the old way
Traceback (most recent call last):
  File "/afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/FCCAnalyses/bin/fccanalysis", line 37, in <module>
    run(parser)
  File "/afs/cern.ch/work/a/atishelm/private/FCC/BNL-Analyses/FCCAnalyses/config/FCCAnalysisRun.py", line 1102, in run
    if args.final:
AttributeError: 'Namespace' object has no attribute 'final'
```

Thoughts? Thanks!

### CODE REVIEW

**Comment by kjvbrt** [comment]
Hello @atishelmanch,

The errors point to the problem in routing of the sub-commands/parameters. Can you share your stage1.py file as well?

**Comment by atishelmanch** [comment]
Thanks for the reply @kjvbrt - yes, you can find the stage1 file attached here:

[ZccH_stage1.py.txt](https://github.com/HEP-FCC/FCCAnalyses/files/10992193/ZccH_stage1.py.txt)

Where the issue came up because both `jetFlavourHelper.outputBranches()` and (I think) `variables_jet` contain `jet_nmu`, so the solution was just removing `branchList += jetFlavourHelper.outputBranches()` from the configuration file.

**Comment by kjvbrt** [comment]
Thanks @atishelmanch, I'm missing yaml config file :)

**Comment by atishelmanch** [comment]
Ah of course :) here @kjvbrt : 

[RunConfig.yaml.txt](https://github.com/HEP-FCC/FCCAnalyses/files/10992868/RunConfig.yaml.txt)

**Comment by kjvbrt** [comment]
Thanks @atishelmanch,

with this PR https://github.com/HEP-FCC/FCCAnalyses/pull/256 I'm getting output like this:
```
17:14:18 [jsmiesko@carriacou FCCAnalyses (master *%=)]$ fccanalysis run ZccH_stage1.py 
----> Info: Loading analysis file:
      /home/jsmiesko/Work/FCC/FCCAnalyses/ZccH_stage1.py
batch: 0
EOSoutput: 0
name: ZccH_4jetsRequired
njets: 4
The variable <outputDirEos> is optional in your analysis.py file, return default empty string
----> yaml file /cvmfs/fcc.cern.ch/FCCDicts/yaml/FCCee/winter2023/IDEA/p8_ee_Zqq_ecm240/merge.yaml succesfu
lly opened
----> Running process p8_ee_Zqq_ecm240 with fraction=0.0025, output=p8_ee_Zqq_ecm240, chunks=20
----> Running Locally
----> Create dataframe object from files: 
    /eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA/p8_ee_Zqq_ecm240/events_005174489.root
----> nevents original=0  local=100000
----> Info: Loading analyzers from libFCCAnalyses... 
The variable <geometryFile> is optional in your analysis.py file, return default value empty string
The variable <readoutName> is optional in your analysis.py file, return default value empty string
----> Init done, about to run 100000 events on 8 CPUs
----> Error: During the execution of the stage file:
      /home/jsmiesko/Work/FCC/FCCAnalyses/ZccH_stage1.py
      exception occurred:
Template method resolution failed:
  none of the 3 overloaded methods succeeded. Full details:
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface
<ROOT::Detail::RDF::RLoopManager,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic
_string_view<char,char_traits<char> > filename, initializer_list<string> columnList, const ROOT::RDF::RSnap
shotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    TypeError: could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface
<ROOT::Detail::RDF::RLoopManager,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic
_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapsho
tOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    runtime_error: Unknown column: event_invariant_mass
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface
<ROOT::Detail::RDF::RLoopManager,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic
_string_view<char,char_traits<char> > filename, basic_string_view<char,char_traits<char> > columnNameRegexp
 = "", const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    TypeError: could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface
<ROOT::Detail::RDF::RLoopManager,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic
_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapsho
tOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    runtime_error: Unknown column: event_invariant_mass
  Failed to instantiate "Snapshot(std::string,std::string,std::vector<string>*)"
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface
<ROOT::Detail::RDF::RLoopManager,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic
_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapsho
tOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    runtime_error: Unknown column: event_invariant_mass
```
I believe it conveys enough information about the error in the stage file.

The problem with the current master is that it catches all possible errors in all stages. If exception occurs it reroutes into the legacy mode.

**Comment by atishelmanch** [comment]
Hello - yes this is definitely enough information now, and your explanation makes sense. So would you propose closing this MR in favor of https://github.com/HEP-FCC/FCCAnalyses/pull/256 ?

**Comment by kjvbrt** [comment]
Yes, but thanks for pointing out the problem :)

Event with https://github.com/HEP-FCC/FCCAnalyses/pull/256 the routing of the sub-commands could be wonky so if you encounter a problem let us know.

**Comment by atishelmanch** [comment]
closing in favor of https://github.com/HEP-FCC/FCCAnalyses/pull/256

**Pull request closed without merging**
