### PR TITLE
simple script to read podio CollectionID table from reco file

### PR DESCRIPTION
**Pull request by portalesHEP**
Very basic script allowing to get the proper `CollectionIDs` for a given file.

Runs by default on a `winter2023` pythia8 ee->ZZ sample, but can take as `--input` argument any sample the user may need.

@selvaggi fyi

### CODE REVIEW

**Comment by kjvbrt** [comment]
I believe this is something which should be handled by the `podio-dump` utility. Let's see how the https://github.com/AIDASoft/podio/pull/373 will go.

**Comment by portalesHEP** [comment]
Sorry to come back to this this late, but how should this be handled then? It would seem useful to have some up-to-date (or at least pointers to) recipes somewhere in here.

**Comment by kjvbrt** [comment]
I believe the README edit would be enough.

The example usage of the `podio-dump`:
```
16:20:15 [jsmiesko@carriacou FCCAnalyses (master=)]$ podio-dump /eos/experiment/fcc/ee/generation/DelphesStandalone/Edm4Hep/pre_winter2023_tests_v2/wzp6_ee_nunuH_Hbb_ecm240/events_1.root                            
input file: /eos/experiment/fcc/ee/generation/DelphesStandalone/Edm4Hep/pre_winter2023_tests_v2/wzp6_ee_nunuH_Hbb_ecm240/events_1.root

Frame categories in this file:
Name                 Entries   
-------------------------------
events               100000    

#################################### events 0 ####################################
Collections:
Name                                   ID   Type                             Size      
----------------------------------------------------------------------------------
EFlowNeutralHadron                     12   edm4hep::Cluster                 0         
MissingET                              1    edm4hep::ReconstructedParticle   1         
MCRecoAssociations                     2    edm4hep::MCRecoParticleAssociation 32        
ParticleIDs                            3    edm4hep::ParticleID              19        
TrackerHits                            4    edm4hep::TrackerHit              51        
EFlowTrack                             5    edm4hep::Track                   17        
CalorimeterHits                        6    edm4hep::CalorimeterHit          15        
ReconstructedParticles                 14   edm4hep::ReconstructedParticle   32        
Jet                                    13   edm4hep::ReconstructedParticle   2         
Muon                                   15   edm4hep::ReconstructedParticle   0         
Particle                               7    edm4hep::MCParticle              79        
Electron                               8    edm4hep::ReconstructedParticle   1         
Photon                                 11   edm4hep::ReconstructedParticle   0         
EFlowTrack_L                           10   float                            17        
EFlowPhoton                            9    edm4hep::Cluster                 15        

Parameters:
Name                           Type         Elements  
------------------------------------------------------
```

The version of the `podio-dump` with the IDs is available in the nighties ATM.

**Comment by portalesHEP** [comment]
Ok, thanks! Then wouldn't it make more sense to close this PR and opening an issue reminding us to update the README once the ID dump is implemented in the default `podio-dump`'s version we use with `FCCAnalysis` ? Or instead would you rather have `podio-dump` mentioned here already (maybe with a warning of some sort that the feature is only in the nighties for now)?

**Comment by kjvbrt** [comment]
Let's keep the PR open, just edit it with the mention of `podio-dump` instead of the custom script. When the proper version of `podio-dump` will be ready the PR will be merged. :)

**Comment by kjvbrt** [comment]
Moving the script into the AuxTools:
https://github.com/HEP-FCC/AuxTools/pull/1

**Pull request merged**
