### PR TITLE
Adding di higgs analyses

### PR DESCRIPTION
**Pull request by selvaggi**

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi Michele! Thanks for the update. I see some binary files in there. Can you remove the `*.pcm` and `*.o` files and rebase?

**Comment by selvaggi** [comment]
Hi Valentin,

the so files were needed to compute the mT2 variable, I have removed them.
But it is probably better to keep the .x file that allows to create the shared object.

**Comment by vvolkl** [comment]
Thanks! ah, yes, then  keeping the .x files makes sense. Can you still  rebase your branch and squash all commits, for example with 
```git reset --soft master
 git commit
git push -f
```
? Otherwise git still keeps track of the binary files, and they will be downloaded on every `git clone`.

**Comment by clementhelsens** [comment]
@selvaggi, could you please apply the changes suggested by @vvolkl  so that we can merge this PR?

**Comment by vvolkl** [comment]
This is superseded by  #24

**Pull request closed without merging**
