### PR TITLE
weaver: run example singlethreaded

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Comment by forthommel** [comment]
Likely that with the merge of #196 this can safely be reverted.

**Comment by clementhelsens** [comment]
or maybe just change it again to >1 in #196 ?

**Comment by forthommel** [comment]
Sure! Though I don't want to spoil this repo's history :)

**Comment by vvolkl** [comment]
Thanks for paying attention to a readable commit history :) in this case I think you can just go ahead and change it back in  #196

**Pull request merged**
